services:
  demo10-api:
    build: .
    container_name: demo10-api
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production
    depends_on:
      - demo10-db

  demo10-db:
    image: mongo:6
    container_name: demo10-db
    restart: always
    volumes:
      - demo10_data:/data/db

volumes:
  demo10_data:
